Fix: 以下のエラーによると､関数には2つの引数をいれなくてはならなかった｡しかし､引数に何もなかったため､エラーが出たと考えられる｡
頑張れ!!

TypeError: str_combine() missing 2 required positional arguments: 'name' and 'family_name'